image: Visual Studio 2017
version: "{build}"

skip_tags: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 $env:platform
  - yarn global add prebuild
  - yarn install

build_script:
  - node --version
  - yarn --version
  - prebuild -r electron --arch ia32 -t 3.0.4 -t 4.0.0 -t 5.0.1 -u %github_token%
  - prebuild -r electron --arch x64 -t 3.0.4 -t 4.0.0 -t 5.0.1 -u %github_token%

test: off

environment:
  github_token:
    secure: NcZvncAoabpEOygUWF0I8Y8/xZAQruWadpQIOibJMeEd1QDtCqKbrmJdHFgSnlRG
